# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - step:
      type: Run
      identifier: build_javascript_app
      name: Build JavaScript App
      spec:
        shell: Sh
        command: |-
          echo "Welcome to Harness CI"
          node --version
          npm install
          npm run build --if-present
          npm test
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'fsdfsd'
    arguments: '1111'
